function displayTrajErrs( learningOutput, obs_info, solver_info )

fprintf(['\n------------------- Trajectory accuracies, same IC''s as training data:' ...
    '\n\tsup-norm  on [%10.4e,%10.4e], mean = %10.4e%c%10.4e, std = %10.4e%c%10.4e' ...
    '\n\tsup-norm  on [%10.4e,%10.4e], mean = %10.4e%c%10.4e, std = %10.4e%c%10.4e'], ...
    0,            obs_info.T_L,             mean(cellfun(@(x) mean(x.trajErr.sup),     learningOutput)), 177, std(cellfun(@(x) mean(x.trajErr.sup),     learningOutput)), ...
    mean(cellfun(@(x) std( x.trajErr.sup),     learningOutput)), 177, std(cellfun(@(x) std( x.trajErr.sup),     learningOutput)), ...
    obs_info.T_L, solver_info.time_span(2), mean(cellfun(@(x) mean(x.trajErr.sup_fut), learningOutput)), 177, std(cellfun(@(x) mean(x.trajErr.sup_fut), learningOutput)), ...
    mean(cellfun(@(x) std( x.trajErr.sup_fut), learningOutput)), 177, std(cellfun(@(x) std( x.trajErr.sup_fut), learningOutput)));

fprintf(['\n------------------- Trajectory accuracies, new IC''s:' ...
    '\n\tsup-norm  on [%10.4e,%10.4e], mean = %10.4e%c%10.4e, std = %10.4e%c%10.4e' ...
    '\n\tsup-norm  on [%10.4e,%10.4e], mean = %10.4e%c%10.4e, std = %10.4e%c%10.4e'], ...
    0,            obs_info.T_L,             mean(cellfun(@(x) mean(x.trajErr_new.sup),     learningOutput)), 177, std(cellfun(@(x) mean(x.trajErr_new.sup),     learningOutput)), ...
    mean(cellfun(@(x) std( x.trajErr_new.sup),     learningOutput)), 177, std(cellfun(@(x) std( x.trajErr_new.sup),     learningOutput)), ...
    obs_info.T_L, solver_info.time_span(2), mean(cellfun(@(x) mean(x.trajErr_new.sup_fut), learningOutput)), 177, std(cellfun(@(x) mean(x.trajErr_new.sup_fut), learningOutput)), ...
    mean(cellfun(@(x) std( x.trajErr_new.sup_fut), learningOutput)), 177, std(cellfun(@(x) std( x.trajErr_new.sup_fut), learningOutput)));

if isfield(learningOutput{1}, 'trajErr_Ntransfer') && ~isempty(learningOutput{1}.trajErr_Ntransfer)
    fprintf(['\n------------------- Trajectory accuracies, larger N:' ...
        '\n\tsup-norm  on [%10.4e,%10.4e], mean = %10.4e%c%10.4e, std = %10.4e%c%10.4e' ...
        '\n\tsup-norm  on [%10.4e,%10.4e], mean = %10.4e%c%10.4e, std = %10.4e%c%10.4e'], ...
        0,            obs_info.T_L,             mean(cellfun(@(x) mean(x.trajErr_Ntransfer.sup),     learningOutput)), 177, std(cellfun(@(x) mean(x.trajErr_Ntransfer.sup),     learningOutput)), ...
        mean(cellfun(@(x) std( x.trajErr_Ntransfer.sup),     learningOutput)), 177, std(cellfun(@(x) std( x.trajErr_Ntransfer.sup),     learningOutput)), ...
        obs_info.T_L, solver_info.time_span(2), mean(cellfun(@(x) mean(x.trajErr_Ntransfer.sup_fut), learningOutput)), 177, std(cellfun(@(x) mean(x.trajErr_Ntransfer.sup_fut), learningOutput)), ...
        mean(cellfun(@(x) std( x.trajErr_Ntransfer.sup_fut), learningOutput)), 177, std(cellfun(@(x) std( x.trajErr_Ntransfer.sup_fut), learningOutput)));
end

return