function u_vec = get_lab_frame_fluid_velocity(x, v, d, N, G)
% function u_vec = get_lab_frame_fluid_velocity(x, v, d, N, G)
% u = u_s + u_p, u_s is the effective stroke-average self-propulsion, u_p is the flow field generated by 
% particle transferring their body force to the fluid, depending on interacting potential \Phi, not
% being considered here, since calculating u_p needs to know phi (the true interaction kernel)

% (C) M. Zhong

% initlization
[R_hat, Rijs, V_hat, Vjs] = get_scaled_quantities(x, v, d, N);
u_vec                     = zeros(N * d, N);
u_mag                     = G * (Vjs./Rijs.^2) .* (3 * get_matrix_dot_product(R_hat, V_hat).^2 - 1);
for idx = 1 : d
  ind                     = idx : d : (N - 1) * d + idx;          
  u_vec(ind, :)           = u_mag .* R_hat(ind, :);
end
u_vec                     = reshape(sum(u_vec, 2), [d, N]);
end