function printOneL2rhoTErr(K, Err, ErrSmooth, kind)
% function printIntKerErr_kind(sys_info.K, Err, ErrSmooth, kind)

% (c) M. Zhong

for k1 = 1 : K
    for k2 = 1 : K
        fprintf(['\n------------------- %s Based Interaction L2(rho_T) Errors -- Relative Errors:' ...
            '\n\tRelative L_2(rho_T) error of original learned estimator for \\phi_{%d, %d} = %10.4e%c%10.4e.' ...
            '\n\tRelative L_2(rho_T) error of smooth   learned estimator for \\phi_{%d, %d} = %10.4e%c%10.4e.'], kind, ...
            k1, k2, mean(cellfun(@(x) x.Rel(k1, k2), Err)),       177, std(cellfun(@(x) x.Rel(k1, k2), Err)), ...
            k1, k2, mean(cellfun(@(x) x.Rel(k1, k2), ErrSmooth)), 177, std(cellfun(@(x) x.Rel(k1, k2), ErrSmooth)));
        fprintf(['\n------------------- %s Based Interaction L2(rho_T) Errors -- Absolute Errors:' ...
            '\n\tAbsolute L_2(rho_T) error of original learned estimator for \\phi_{%d, %d} = %10.4e%c%10.4e.' ...
            '\n\tAbsolute L_2(rho_T) error of smooth   learned estimator for \\phi_{%d, %d} = %10.4e%c%10.4e.'], kind, ...
            k1, k2, mean(cellfun(@(x) x.Abs(k1, k2), Err)),       177, std(cellfun(@(x) x.Abs(k1, k2), Err)), ...
            k1, k2, mean(cellfun(@(x) x.Abs(k1, k2), ErrSmooth)), 177, std(cellfun(@(x) x.Abs(k1, k2), ErrSmooth)));
    end
end

return